### ISSUE TITLE
File "pyrle\src\coverage.pyx", line 28, in pyrle.src.coverage._coverage ValueError: Buffer dtype mismatch, expected 'long' but got 'long long'

### ISSUE THREAD

**Issue by haritha1216-1994** [pyranges/pyrle#7]
Traceback (most recent call last):
  File "c:\Users\HARITHA A\Desktop\work\current work\practise\new.py", line 63, in <module>
    print('midpoint_coverage ',  midpoint_cov(frg_mid_point(frg_flank), sample_file_cov(chr)))
                                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\HARITHA A\Desktop\work\current work\practise\new.py", line 61, in midpoint_cov
    midpoint_coverage = (frg_midpoint_range.to_rle()).astype(np.int64)
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\HARITHA A\anaconda3\envs\sample\Lib\site-packages\pyranges\pyranges_main.py", line 5881, in to_rle
    return _to_rle(self, value_col, strand=strand, rpm=rpm, nb_cpu=nb_cpu)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\HARITHA A\anaconda3\envs\sample\Lib\site-packages\pyranges\methods\to_rle.py", line 18, in _to_rle
    result = pyrange_apply_single(coverage, ranges, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\HARITHA A\anaconda3\envs\sample\Lib\site-packages\pyranges\multithreaded.py", line 342, in pyrange_apply_single
    result = call_f_single(function, nparams, df, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\HARITHA A\anaconda3\envs\sample\Lib\site-packages\pyranges\multithreaded.py", line 28, in call_f_single
    return f.remote(df, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\HARITHA A\anaconda3\envs\sample\Lib\site-packages\pyrle\methods.py", line 154, in coverage
    runs, values = _coverage(_df.Position.values, _df.Value.values)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "pyrle\src\coverage.pyx", line 28, in pyrle.src.coverage._coverage
ValueError: Buffer dtype mismatch, expected 'long' but got 'long long'

**Comment by haritha1216-1994** [comment]
While running to rle () function shows the above errors

**Comment by endrebak** [comment]
I do not have any way to test and debug stuff on windows unfortunately. I'd accept PRs
